version: '3'

services:
  db:
    image: postgres:16.2
    container_name: txn-client-api-db
    environment:
      LANG: en_US.utf8
      POSTGRES_DB: txn-client-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres