# VM options: -Dmicronaut.environments=dev

micronaut:
  port: 8083

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/txn-client-api
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        show_sql: true

