# VM options: -Dmicronaut.environments=dev

micronaut:
  server:
    port: 8400
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000

datasources:
  default:
    url: jdbc:postgresql://localhost:8101/txn-client-db
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        show_sql: true

kafka:
  bootstrap:
    servers: localhost:9092

