micronaut:
  application:
    name: transaction-engine-api
  server:
    netty:
      access-logger:
        enabled: true
        format: combined
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:5432/transaction-engine-api
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create-drop
        connection:
          url: ${datasources.default.url}
          username: ${datasources.default.username}
          password: ${datasources.default.password}
    reactive: true
    
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
